\! tput setaf 1; echo "_______________delete all rows from all tables _________________";
\! tput setaf 2;
delete from friends;
delete from black_list;
delete from balance;
delete from finance;
delete from messages;
delete from chats;
delete from command_structure;
delete from commands;
delete from history_structure;
delete from histories;
delete from users;
